declare global {
  interface Window {
    locationConfigs: LocationConfig[];
  }
}

export type warehouseSize = 'None' | 'Small' | 'Medium' | 'Large' | 'XLarge';
export type officeSize = 'None' | '1 person' | '2 person' | '3 person' | '4 person';

export interface Combination {
  warehouse: warehouseSize;
  office: officeSize;
  total: number;
}

export interface LocationConfig {
  id: string;
  combinations: Combination[];
}

export const locationConfigs: LocationConfig[] = [
  {
    id: 'ATLUW',
    combinations: [
      { warehouse: 'None', office: '1 person', total: 500 },
      { warehouse: 'None', office: '2 person', total: 1000 },
      { warehouse: 'None', office: '3 person', total: 1400 },
      { warehouse: 'None', office: '4 person', total: 1800 },
      { warehouse: 'Small', office: 'None', total: 550 },
      { warehouse: 'Small', office: '1 person', total: 1050 },
      { warehouse: 'Small', office: '2 person', total: 1550 },
      { warehouse: 'Small', office: '3 person', total: 1950 },
      { warehouse: 'Small', office: '4 person', total: 2350 },
      { warehouse: 'Medium', office: 'None', total: 1225 },
      { warehouse: 'Medium', office: '1 person', total: 1725 },
      { warehouse: 'Medium', office: '2 person', total: 2225 },
      { warehouse: 'Medium', office: '3 person', total: 2625 },
      { warehouse: 'Medium', office: '4 person', total: 3025 },
      { warehouse: 'Large', office: 'None', total: 2000 },
      { warehouse: 'Large', office: '1 person', total: 2500 },
      { warehouse: 'Large', office: '2 person', total: 3000 },
      { warehouse: 'Large', office: '3 person', total: 3400 },
      { warehouse: 'Large', office: '4 person', total: 3800 },
      { warehouse: 'XLarge', office: 'None', total: 3800 },
      { warehouse: 'XLarge', office: '1 person', total: 4300 },
      { warehouse: 'XLarge', office: '2 person', total: 4800 },
      { warehouse: 'XLarge', office: '3 person', total: 5200 },
      { warehouse: 'XLarge', office: '4 person', total: 5600 },
    ],
  },
  {
    id: 'ATLWP',
    combinations: [
      { warehouse: 'None', office: '1 person', total: 575 },
      { warehouse: 'None', office: '2 person', total: 1125 },
      { warehouse: 'None', office: '3 person', total: 1550 },
      { warehouse: 'None', office: '4 person', total: 1950 },
      { warehouse: 'Small', office: 'None', total: 575 },
      { warehouse: 'Small', office: '1 person', total: 1150 },
      { warehouse: 'Small', office: '2 person', total: 1700 },
      { warehouse: 'Small', office: '3 person', total: 2125 },
      { warehouse: 'Small', office: '4 person', total: 2525 },
      { warehouse: 'Medium', office: 'None', total: 1350 },
      { warehouse: 'Medium', office: '1 person', total: 1925 },
      { warehouse: 'Medium', office: '2 person', total: 2475 },
      { warehouse: 'Medium', office: '3 person', total: 2900 },
      { warehouse: 'Medium', office: '4 person', total: 3300 },
      { warehouse: 'Large', office: 'None', total: 2400 },
      { warehouse: 'Large', office: '1 person', total: 2975 },
      { warehouse: 'Large', office: '2 person', total: 3525 },
      { warehouse: 'Large', office: '3 person', total: 3950 },
      { warehouse: 'Large', office: '4 person', total: 4350 },
      { warehouse: 'XLarge', office: 'None', total: 4125 },
      { warehouse: 'XLarge', office: '1 person', total: 4700 },
      { warehouse: 'XLarge', office: '2 person', total: 5250 },
      { warehouse: 'XLarge', office: '3 person', total: 5675 },
      { warehouse: 'XLarge', office: '4 person', total: 6075 },
    ],
  },
  {
    id: 'DALC',
    combinations: [
      { warehouse: 'None', office: '1 person', total: 475 },
      { warehouse: 'None', office: '2 person', total: 875 },
      { warehouse: 'None', office: '4 person', total: 1175 },
      { warehouse: 'Small', office: 'None', total: 525 },
      { warehouse: 'Small', office: '1 person', total: 1000 },
      { warehouse: 'Small', office: '2 person', total: 1400 },
      { warehouse: 'Small', office: '4 person', total: 1700 },
      { warehouse: 'Medium', office: 'None', total: 1450 },
      { warehouse: 'Medium', office: '1 person', total: 1925 },
      { warehouse: 'Medium', office: '2 person', total: 2325 },
      { warehouse: 'Medium', office: '4 person', total: 2625 },
      { warehouse: 'Large', office: 'None', total: 2475 },
      { warehouse: 'Large', office: '1 person', total: 2950 },
      { warehouse: 'Large', office: '2 person', total: 3350 },
      { warehouse: 'Large', office: '4 person', total: 3650 },
      { warehouse: 'XLarge', office: 'None', total: 3825 },
      { warehouse: 'XLarge', office: '1 person', total: 4300 },
      { warehouse: 'XLarge', office: '2 person', total: 4700 },
      { warehouse: 'XLarge', office: '4 person', total: 5000 },
    ],
  },
  {
    id: 'DALF',
    combinations: [
      { warehouse: 'None', office: '1 person', total: 475 },
      { warehouse: 'None', office: '2 person', total: 875 },
      { warehouse: 'None', office: '3 person', total: 1175 },
      { warehouse: 'None', office: '4 person', total: 1450 },
      { warehouse: 'Small', office: 'None', total: 850 },
      { warehouse: 'Small', office: '1 person', total: 1325 },
      { warehouse: 'Small', office: '2 person', total: 1725 },
      { warehouse: 'Small', office: '3 person', total: 2025 },
      { warehouse: 'Small', office: '4 person', total: 2300 },
      { warehouse: 'Medium', office: 'None', total: 1400 },
      { warehouse: 'Medium', office: '1 person', total: 1875 },
      { warehouse: 'Medium', office: '2 person', total: 2275 },
      { warehouse: 'Medium', office: '3 person', total: 2575 },
      { warehouse: 'Medium', office: '4 person', total: 2850 },
      { warehouse: 'Large', office: 'None', total: 2475 },
      { warehouse: 'Large', office: '1 person', total: 2950 },
      { warehouse: 'Large', office: '2 person', total: 3350 },
      { warehouse: 'Large', office: '3 person', total: 3650 },
      { warehouse: 'Large', office: '4 person', total: 3925 },
      { warehouse: 'XLarge', office: 'None', total: 3875 },
      { warehouse: 'XLarge', office: '1 person', total: 4350 },
      { warehouse: 'XLarge', office: '2 person', total: 4750 },
      { warehouse: 'XLarge', office: '3 person', total: 5050 },
      { warehouse: 'XLarge', office: '4 person', total: 5325 },
    ],
  },
  {
    id: 'DEN',
    combinations: [
      { warehouse: 'None', office: '1 person', total: 550 },
      { warehouse: 'None', office: '2 person', total: 1000 },
      { warehouse: 'None', office: '3 person', total: 1400 },
      { warehouse: 'None', office: '4 person', total: 1750 },
      { warehouse: 'Small', office: 'None', total: 300 },
      { warehouse: 'Small', office: '1 person', total: 850 },
      { warehouse: 'Small', office: '2 person', total: 1300 },
      { warehouse: 'Small', office: '3 person', total: 1700 },
      { warehouse: 'Small', office: '4 person', total: 2050 },
      { warehouse: 'Medium', office: 'None', total: 1300 },
      { warehouse: 'Medium', office: '1 person', total: 1850 },
      { warehouse: 'Medium', office: '2 person', total: 2300 },
      { warehouse: 'Medium', office: '3 person', total: 2700 },
      { warehouse: 'Medium', office: '4 person', total: 3050 },
      { warehouse: 'Large', office: 'None', total: 2150 },
      { warehouse: 'Large', office: '1 person', total: 2700 },
      { warehouse: 'Large', office: '2 person', total: 3150 },
      { warehouse: 'Large', office: '3 person', total: 3550 },
      { warehouse: 'Large', office: '4 person', total: 3900 },
      { warehouse: 'XLarge', office: 'None', total: 3600 },
      { warehouse: 'XLarge', office: '1 person', total: 4150 },
      { warehouse: 'XLarge', office: '2 person', total: 4600 },
      { warehouse: 'XLarge', office: '3 person', total: 5000 },
      { warehouse: 'XLarge', office: '4 person', total: 5350 },
    ],
  },
  {
    id: 'LAD',
    combinations: [
      { warehouse: 'None', office: '1 person', total: 500 },
      { warehouse: 'None', office: '2 person', total: 740 },
      { warehouse: 'None', office: '3 person', total: 1170 },
      { warehouse: 'None', office: '4 person', total: 1410 },
      { warehouse: 'Small', office: 'None', total: 0 },
      { warehouse: 'Small', office: '1 person', total: 500 },
      { warehouse: 'Small', office: '2 person', total: 740 },
      { warehouse: 'Small', office: '3 person', total: 1170 },
      { warehouse: 'Small', office: '4 person', total: 1410 },
      { warehouse: 'Medium', office: 'None', total: 1800 },
      { warehouse: 'Medium', office: '1 person', total: 2300 },
      { warehouse: 'Medium', office: '2 person', total: 2540 },
      { warehouse: 'Medium', office: '3 person', total: 2970 },
      { warehouse: 'Medium', office: '4 person', total: 3210 },
      { warehouse: 'Large', office: 'None', total: 3100 },
      { warehouse: 'Large', office: '1 person', total: 3600 },
      { warehouse: 'Large', office: '2 person', total: 3840 },
      { warehouse: 'Large', office: '3 person', total: 4270 },
      { warehouse: 'Large', office: '4 person', total: 4510 },
      { warehouse: 'XLarge', office: 'None', total: 5900 },
      { warehouse: 'XLarge', office: '1 person', total: 6400 },
      { warehouse: 'XLarge', office: '2 person', total: 6640 },
      { warehouse: 'XLarge', office: '3 person', total: 7070 },
      { warehouse: 'XLarge', office: '4 person', total: 7310 },
    ],
  },
  {
    id: 'LAT',
    combinations: [
      { warehouse: 'None', office: '1 person', total: 600 },
      { warehouse: 'None', office: '2 person', total: 1000 },
      { warehouse: 'None', office: '3 person', total: 1300 },
      { warehouse: 'None', office: '4 person', total: 1600 },
      { warehouse: 'Small', office: 'None', total: 775 },
      { warehouse: 'Small', office: '1 person', total: 1375 },
      { warehouse: 'Small', office: '2 person', total: 1775 },
      { warehouse: 'Small', office: '3 person', total: 2075 },
      { warehouse: 'Small', office: '4 person', total: 2375 },
      { warehouse: 'Medium', office: 'None', total: 2050 },
      { warehouse: 'Medium', office: '1 person', total: 2650 },
      { warehouse: 'Medium', office: '2 person', total: 3050 },
      { warehouse: 'Medium', office: '3 person', total: 3350 },
      { warehouse: 'Medium', office: '4 person', total: 3650 },
      { warehouse: 'Large', office: 'None', total: 3700 },
      { warehouse: 'Large', office: '1 person', total: 4300 },
      { warehouse: 'Large', office: '2 person', total: 4700 },
      { warehouse: 'Large', office: '3 person', total: 5000 },
      { warehouse: 'Large', office: '4 person', total: 5300 },
      { warehouse: 'XLarge', office: 'None', total: 5450 },
      { warehouse: 'XLarge', office: '1 person', total: 6050 },
      { warehouse: 'XLarge', office: '2 person', total: 6450 },
      { warehouse: 'XLarge', office: '3 person', total: 6750 },
      { warehouse: 'XLarge', office: '4 person', total: 7050 },
    ],
  },
  {
    id: 'MIA',
    combinations: [
      { warehouse: 'None', office: '1 person', total: 775 },
      { warehouse: 'None', office: '2 person', total: 1075 },
      { warehouse: 'None', office: '4 person', total: 1550 },
      { warehouse: 'Small', office: 'None', total: 875 },
      { warehouse: 'Small', office: '1 person', total: 1650 },
      { warehouse: 'Small', office: '2 person', total: 1950 },
      { warehouse: 'Small', office: '4 person', total: 2425 },
      { warehouse: 'Medium', office: 'None', total: 2175 },
      { warehouse: 'Medium', office: '1 person', total: 2950 },
      { warehouse: 'Medium', office: '2 person', total: 3250 },
      { warehouse: 'Medium', office: '4 person', total: 3725 },
      { warehouse: 'Large', office: 'None', total: 3500 },
      { warehouse: 'Large', office: '1 person', total: 4275 },
      { warehouse: 'Large', office: '2 person', total: 4575 },
      { warehouse: 'Large', office: '4 person', total: 5050 },
      { warehouse: 'XLarge', office: 'None', total: 5650 },
      { warehouse: 'XLarge', office: '1 person', total: 6425 },
      { warehouse: 'XLarge', office: '2 person', total: 6725 },
      { warehouse: 'XLarge', office: '4 person', total: 7200 },
    ],
  },
  {
    id: 'MIN',
    combinations: [
      { warehouse: 'Small', office: 'None', total: 550 },
      { warehouse: 'Medium', office: 'None', total: 1300 },
      { warehouse: 'Large', office: 'None', total: 2100 },
      { warehouse: 'XLarge', office: 'None', total: 3600 },
    ],
  },
  {
    id: 'PHO',
    combinations: [
      { warehouse: 'None', office: '1 person', total: 550 },
      { warehouse: 'None', office: '2 person', total: 850 },
      { warehouse: 'None', office: '4 person', total: 1800 },
      { warehouse: 'Small', office: 'None', total: 500 },
      { warehouse: 'Small', office: '1 person', total: 1050 },
      { warehouse: 'Small', office: '2 person', total: 1350 },
      { warehouse: 'Small', office: '4 person', total: 2300 },
      { warehouse: 'Medium', office: 'None', total: 1500 },
      { warehouse: 'Medium', office: '1 person', total: 2050 },
      { warehouse: 'Medium', office: '2 person', total: 2350 },
      { warehouse: 'Medium', office: '4 person', total: 3300 },
      { warehouse: 'Large', office: 'None', total: 2500 },
      { warehouse: 'Large', office: '1 person', total: 3050 },
      { warehouse: 'Large', office: '2 person', total: 3350 },
      { warehouse: 'Large', office: '4 person', total: 4300 },
      { warehouse: 'XLarge', office: 'None', total: 4200 },
      { warehouse: 'XLarge', office: '1 person', total: 4750 },
      { warehouse: 'XLarge', office: '2 person', total: 5050 },
      { warehouse: 'XLarge', office: '4 person', total: 6000 },
    ],
  },
  {
    id: 'SEA',
    combinations: [
      { warehouse: 'Small', office: 'None', total: 375 },
      { warehouse: 'Medium', office: 'None', total: 1700 },
      { warehouse: 'Large', office: 'None', total: 2575 },
      { warehouse: 'XLarge', office: 'None', total: 4000 },
    ],
  },
  {
    id: 'WASH',
    combinations: [
      { warehouse: 'None', office: '1 person', total: 725 },
      { warehouse: 'None', office: '2 person', total: 1025 },
      { warehouse: 'None', office: '3 person', total: 1450 },
      { warehouse: 'None', office: '4 person', total: 1850 },
      { warehouse: 'Small', office: 'None', total: 725 },
      { warehouse: 'Small', office: '1 person', total: 1450 },
      { warehouse: 'Small', office: '2 person', total: 1750 },
      { warehouse: 'Small', office: '3 person', total: 2175 },
      { warehouse: 'Small', office: '4 person', total: 2575 },
      { warehouse: 'Medium', office: 'None', total: 1975 },
      { warehouse: 'Medium', office: '1 person', total: 2700 },
      { warehouse: 'Medium', office: '2 person', total: 3000 },
      { warehouse: 'Medium', office: '3 person', total: 3425 },
      { warehouse: 'Medium', office: '4 person', total: 3825 },
      { warehouse: 'Large', office: 'None', total: 3300 },
      { warehouse: 'Large', office: '1 person', total: 4025 },
      { warehouse: 'Large', office: '2 person', total: 4325 },
      { warehouse: 'Large', office: '3 person', total: 4750 },
      { warehouse: 'Large', office: '4 person', total: 5150 },
      { warehouse: 'XLarge', office: 'None', total: 5450 },
      { warehouse: 'XLarge', office: '1 person', total: 6175 },
      { warehouse: 'XLarge', office: '2 person', total: 6475 },
      { warehouse: 'XLarge', office: '3 person', total: 6900 },
      { warehouse: 'XLarge', office: '4 person', total: 7300 },
    ],
  },
];
